### ISSUE TITLE
Newsletter - Design

### ISSUE THREAD

**Issue by gokulkrishh** [code-kotis/this-week-in-web#1]
- Create a design. May be using sketch ?

**Comment by gokulkrishh** [comment]
**Design**:

![screenshot 2019-02-06 at 7 27 52 pm](https://user-images.githubusercontent.com/2944237/52389483-b8d82480-2ab9-11e9-9dcb-ec10e4511484.png)

**Actually how it will look in site**:

![screenshot 2019-02-06 at 10 04 40 pm](https://user-images.githubusercontent.com/2944237/52389501-c68daa00-2ab9-11e9-8315-090c7d59d956.png)

**Comment by shidhincr** [comment]
👍 Let's implement this.. Thanks @gokulkrishh
