### ISSUE TITLE
Fix the 404 and 50* page template

### ISSUE THREAD

**Issue by shidhincr** [code-kotis/this-week-in-web#20]
The 404 pages are broken as of now. We need to fix the styling.

**Comment by gokulkrishh** [comment]
@shidhincr Can you pls post a screenshot for ref ?


This is what i see for 404

<img width="1680" alt="screen shot 2019-02-25 at 3 34 20 pm" src="https://user-images.githubusercontent.com/2944237/53329792-e4109f80-3912-11e9-9dd7-a9eeb9a2076d.png">

**Comment by shidhincr** [comment]
Yeah.. this is working. May be I've tested the local dev one.

**Comment by shidhincr** [comment]
closing this issue then.

**Comment by gokulkrishh** [comment]
Cool!
